/*******************************************************************************
 * Copyright 2013 Imperial College London
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.imperial.clahrc.entity;

// Generated 09-Nov-2011 21:46:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;

/**
 * LoginAuditId generated by hbm2java
 */
@Embeddable
public class LoginAuditId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int userId;
	private String sessionId;
	private String ipAddress;
	private Date loggedInDateTime;

	public LoginAuditId() {
	}

	public LoginAuditId(int userId, String sessionId, String ipAddress, Date loggedInDateTime) {
		this.userId = userId;
		this.sessionId = sessionId;
		this.ipAddress = ipAddress;
		this.loggedInDateTime = loggedInDateTime;
	}

	@Column(name = "User_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "Session_ID", unique = true, nullable = false, length = 45)
	@NotNull
	@Size(max = 45)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "IP_Address", nullable = false, length = 15)
    @NotNull
    @Size(max = 15)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
	@Column(name = "LoggedIn_DateTime", nullable = false, length = 19)
	@NotNull
	public Date getLoggedInDateTime() {
		return this.loggedInDateTime;
	}

	public void setLoggedInDateTime(Date loggedInDateTime) {
		this.loggedInDateTime = loggedInDateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginAuditId))
			return false;
		LoginAuditId castOther = (LoginAuditId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getSessionId() == castOther.getSessionId()) || 
					(this.getSessionId() != null && castOther.getSessionId() != null && 
					 this.getSessionId().equals(castOther.getSessionId())))
				&& ((this.getIpAddress() == castOther.getIpAddress()) ||
					(this.getIpAddress() != null && castOther.getIpAddress() != null &&
					 this.getIpAddress().equals(castOther.getIpAddress())))
				&& ((this.getLoggedInDateTime() == castOther.getLoggedInDateTime()) || 
					(this.getLoggedInDateTime() != null && 
					 castOther.getLoggedInDateTime() != null && 
					 this.getLoggedInDateTime().equals(castOther.getLoggedInDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		result = 37 * result + ( getIpAddress() == null ? 0 : this.getIpAddress().hashCode());
		result = 37 * result + (getLoggedInDateTime() == null ? 0 : this.getLoggedInDateTime().hashCode());
		return result;
	}

}
