/*******************************************************************************
 * Copyright 2013 Imperial College London
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.imperial.clahrc.entity;

// Generated 09-Nov-2011 21:46:06 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;

/**
 * Milestone generated by hbm2java
 */
@Entity
@Table(name = "milestone", catalog = "clahrc2")
public class Milestone implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Date milestoneDate;
	private String label;
	private String description;
	private String milestoneType;
	private Date rcTimestamp;

	public Milestone() {
	}

	public Milestone(Date milestoneDate, String milestoneType, Date rcTimestamp) {
		this.milestoneDate = milestoneDate;
		this.milestoneType = milestoneType;
		this.rcTimestamp = rcTimestamp;
	}

	public Milestone(Date milestoneDate, String label, String description,
			String milestoneType, Date rcTimestamp) {
		this.milestoneDate = milestoneDate;
		this.label = label;
		this.description = description;
		this.milestoneType = milestoneType;
		this.rcTimestamp = rcTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Milestone_Date", nullable = false, length = 10)
	@NotNull
	public Date getMilestoneDate() {
		return this.milestoneDate;
	}

	public void setMilestoneDate(Date milestoneDate) {
		this.milestoneDate = milestoneDate;
	}

	@Column(name = "Label", length = 45)
	@Size(max = 45)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "Description", length = 45)
	@Size(max = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Milestone_Type", nullable = false, length = 45)
	@NotNull
	@Size(max = 45)
	public String getMilestoneType() {
		return this.milestoneType;
	}

	public void setMilestoneType(String milestoneType) {
		this.milestoneType = milestoneType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Rc_Timestamp", nullable = false, length = 19)
	public Date getRcTimestamp() {
		return this.rcTimestamp;
	}

	public void setRcTimestamp(Date rcTimestamp) {
		this.rcTimestamp = (rcTimestamp == null ? new Timestamp(Calendar.getInstance().getTimeInMillis()) : rcTimestamp);
	}

}
