/*******************************************************************************
 * Copyright 2013 Imperial College London
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.imperial.clahrc.entity;
// Generated 17-May-2012 13:33:54 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;

/**
 * ProjectTablesId generated by hbm2java
 */
@Embeddable
public class ProjectTablesId  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int projectId;
    private String tableName;

    public ProjectTablesId() {
    }

    public ProjectTablesId(int projectId, String tableName) {
       this.projectId = projectId;
       this.tableName = tableName;
    }
   


    @Column(name="Project_ID", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


    @Column(name="Table_Name", unique=true, nullable=false, length=45)
    @NotNull
    @Size(max=45)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectTablesId) ) return false;
		 ProjectTablesId castOther = ( ProjectTablesId ) other; 
         
		 return (this.getProjectId()==castOther.getProjectId())
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProjectId();
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         return result;
   }   


}


