/*******************************************************************************
 * Copyright 2013 Imperial College London
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.imperial.clahrc.entity;

// Generated 10-Nov-2011 15:22:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "clahrc2", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class Roles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String description;
	private Set<UserProjectRoles> userProjectRoleses = new HashSet<UserProjectRoles>(0);
    private Set<UserProjectRoleRequests> userProjectRoleRequestses = new HashSet<UserProjectRoleRequests>(0);
    private Set<UserProjectRolesAudit> userProjectRolesAudits = new HashSet<UserProjectRolesAudit>(0);

	public Roles() {
	}

	public Roles(String name) {
		this.name = name.trim();
	}

	public Roles(String name, String description,
			Set<UserProjectRoles> userProjectRoleses,
			Set<UserProjectRoleRequests> userProjectRoleRequestses, 
			Set<UserProjectRolesAudit> userProjectRolesAudits) {
		this.name = name.trim();
		this.description = description;
		this.userProjectRoleses = userProjectRoleses;
	    this.userProjectRoleRequestses = userProjectRoleRequestses;
	    this.userProjectRolesAudits = userProjectRolesAudits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 45)
	@NotNull
	@Size(max = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name.trim();
	}

	@Column(name = "Description", length = 10000)
	@Size(max = 10000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<UserProjectRoles> getUserProjectRoleses() {
		return this.userProjectRoleses;
	}

	public void setUserProjectRoleses(Set<UserProjectRoles> userProjectRoleses) {
		this.userProjectRoleses = userProjectRoleses;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<UserProjectRoleRequests> getUserProjectRoleRequestses() {
        return this.userProjectRoleRequestses;
    }
    
    public void setUserProjectRoleRequestses(Set<UserProjectRoleRequests> userProjectRoleRequestses) {
        this.userProjectRoleRequestses = userProjectRoleRequestses;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<UserProjectRolesAudit> getUserProjectRolesAudits() {
        return this.userProjectRolesAudits;
    }
    
    public void setUserProjectRolesAudits(Set<UserProjectRolesAudit> userProjectRolesAudits) {
        this.userProjectRolesAudits = userProjectRolesAudits;
    }
}
