/*******************************************************************************
 * Copyright 2013 Imperial College London
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.imperial.clahrc.entity;
// Generated 17-May-2012 13:33:54 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;

/**
 * UsersUserProjectRolesId generated by hbm2java
 */
@Embeddable
public class UsersUserProjectRolesId  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int id;
    private String firstName;
    private String lastName;
    private Date registrationDate;
    private boolean active;
    private String loginName;
    private String password;
    private String email;
    private int userId;
    private int projectId;
    private int roleId;

    public UsersUserProjectRolesId() {
    }

    public UsersUserProjectRolesId(int id, String firstName, String lastName, Date registrationDate, boolean active, String loginName, String password, String email, int userId, int projectId, int roleId) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.registrationDate = registrationDate;
       this.active = active;
       this.loginName = loginName;
       this.password = password;
       this.email = email;
       this.userId = userId;
       this.projectId = projectId;
       this.roleId = roleId;
    }
   


    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="First_Name", nullable=false, length=45)
    @NotNull
    @Size(max=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    @Column(name="Last_Name", nullable=false, length=45)
    @NotNull
    @Size(max=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    @Column(name="Registration_Date", nullable=false, length=10)
    @NotNull
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }


    @Column(name="Active", nullable=false, columnDefinition = "BIT")
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }


    @Column(name="Login_Name", nullable=false, length=45)
    @NotNull
    @Size(max=45)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }


    @Column(name="Password", nullable=false, length=45)
    @NotNull
    @Size(max=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


    @Column(name="Email", nullable=false, length=45)
    @NotNull
    @Size(max=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="User_ID", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="Project_ID", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


    @Column(name="Role_ID", nullable=false)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersUserProjectRolesId) ) return false;
		 UsersUserProjectRolesId castOther = ( UsersUserProjectRolesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getFirstName()==castOther.getFirstName()) || ( this.getFirstName()!=null && castOther.getFirstName()!=null && this.getFirstName().equals(castOther.getFirstName()) ) )
 && ( (this.getLastName()==castOther.getLastName()) || ( this.getLastName()!=null && castOther.getLastName()!=null && this.getLastName().equals(castOther.getLastName()) ) )
 && ( (this.getRegistrationDate()==castOther.getRegistrationDate()) || ( this.getRegistrationDate()!=null && castOther.getRegistrationDate()!=null && this.getRegistrationDate().equals(castOther.getRegistrationDate()) ) )
 && (this.isActive()==castOther.isActive())
 && ( (this.getLoginName()==castOther.getLoginName()) || ( this.getLoginName()!=null && castOther.getLoginName()!=null && this.getLoginName().equals(castOther.getLoginName()) ) )
 && ( (this.getPassword()==castOther.getPassword()) || ( this.getPassword()!=null && castOther.getPassword()!=null && this.getPassword().equals(castOther.getPassword()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && (this.getUserId()==castOther.getUserId())
 && (this.getProjectId()==castOther.getProjectId())
 && (this.getRoleId()==castOther.getRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getFirstName() == null ? 0 : this.getFirstName().hashCode() );
         result = 37 * result + ( getLastName() == null ? 0 : this.getLastName().hashCode() );
         result = 37 * result + ( getRegistrationDate() == null ? 0 : this.getRegistrationDate().hashCode() );
         result = 37 * result + (this.isActive()?1:0);
         result = 37 * result + ( getLoginName() == null ? 0 : this.getLoginName().hashCode() );
         result = 37 * result + ( getPassword() == null ? 0 : this.getPassword().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getProjectId();
         result = 37 * result + this.getRoleId();
         return result;
   }   


}


