/*******************************************************************************
 * Copyright 2013 Imperial College London
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.imperial.clahrc.entity;
// Generated 22-Oct-2012 11:15:44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserProjectRolesId generated by hbm2java
 */
@Embeddable
public class UserProjectRolesId  implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	
	private int userId;
    private int projectId;

    public UserProjectRolesId() {
    }

    public UserProjectRolesId(int userId, int projectId) {
       this.userId = userId;
       this.projectId = projectId;
    }
   


    @Column(name="User_ID", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="Project_ID", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserProjectRolesId) ) return false;
		 UserProjectRolesId castOther = ( UserProjectRolesId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getProjectId()==castOther.getProjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getProjectId();
         return result;
   }   


}


